Add mango coconut rice recipe
diego-codes/recipes pull request #10
Opened 2020-05-04 03:29 UTC by NicMoe

2020-05-16 18:13 UTC, diego-codes reviewed
I have questions

2020-05-16 18:13 UTC, diego-codes commented on desserts/mango-coconut-rice.md
> +- 1.5 cups long-grain rice (ideally sushi rice)
Sushi rice is a type of short-grain rice. Which is it then?

2020-05-16 18:13 UTC, diego-codes commented on desserts/mango-coconut-rice.md
> +- 1 tablespoon olive oil
Should these measurements use abbreviations? It is how we have other recipes here.

2020-05-16 18:13 UTC, diego-codes commented on desserts/mango-coconut-rice.md
> +- 1 tablespoon olive oil
I love olive oil, but is it really the right type of oil for this? It's too flavorful IMO. Also, Thai food would definitely not use olive oil.

2020-05-16 18:13 UTC, diego-codes commented on desserts/mango-coconut-rice.md
> +3. Add cubed mango to pan, tossing gently. Cook 10 minutes or until mango is lightly browned, stirring frequently.
So my idea of caramelizing mangoes would only apply to frozen and unripe mango. When they're ripe they are already sweet and probably don't need any more sugar.

2020-05-16 19:51 UTC, NicMoe commented on desserts/mango-coconut-rice.md
> +- 1 tablespoon olive oil
```suggestion
- 1 tbsp olive oil
```

2020-05-16 21:58 UTC, diego-codes requested changes

2020-05-16 21:58 UTC, diego-codes commented on desserts/mango-coconut-rice.md
> +3. In another large saucepan, heat the tablespoon of olive oil over medium-high heat. Stir in the 1.5 cups of rice to coat with the oil.
```suggestion
3. In another large saucepan, heat the tablespoon of oil over medium-high heat. Stir in the 1.5 cups of rice to coat with the oil.
```

2020-05-16 21:58 UTC, diego-codes commented on desserts/mango-coconut-rice.md
> +4. Add the can of coconut milk, 1/2 cup water, and teaspoon of salt; bring to a boil. Stir in the caramelized mango.
```suggestion
4. Add the can of coconut milk, 1/2 cup water, and teaspoon of salt; bring to a boil. Stir in the mango.
```

2020-09-12 23:31 UTC, NicMoe commented
@diego-codes please review and merge if good.

2020-10-22 17:20 UTC, diego-codes approved these changes

2020-10-22 17:20 UTC, merged