Added development doc link
diego-codes/recipes pull request #14
Opened 2020-07-20 02:12 UTC by NicMoe

2020-09-12 20:28 UTC, diego-codes requested changes

2020-09-12 20:28 UTC, diego-codes commented on README.md
> +For recipes in development, check out [this document](https://docs.google.com/document/d/1xt3ZELFwRy-5zbsjgJlqxuL6pR6px2PWvsmN4Wd8rmI/edit?usp=sharing).
I'm pretty sure that this document is generated by the python script so you'll want to add this into the script so it doesn't get erased next time we update the readme.

2020-09-12 23:36 UTC, NicMoe commented
@diego-codes please review and merge if good.

2020-09-13 00:25 UTC, NicMoe commented
I included this change appropriately within the README generator doc in https://github.com/diego-codes/recipes/pull/10. Closing this PR.

2020-09-13 00:25 UTC, closed without merging