Add sautéed kale recipe
diego-codes/recipes pull request #6
Opened 2020-02-17 03:35 UTC by diego-codes

2020-02-17 04:24 UTC, NicMoe commented on soup/white-bean-brothy-soup.md
> +
add space

2020-02-17 04:24 UTC, NicMoe commented on sides/sauteed-kale.md
> +- 1/3 of a bag of chopped kale (enough to cover the entire pan)
how big is the bag?

2020-02-17 04:27 UTC, NicMoe commented on soup/white-bean-brothy-soup.md
> +# White bean brothy soup
I feel like this recipe should be called "brothy white bean soup" instead

2020-02-17 04:28 UTC, NicMoe requested changes
Overall looks good. Check out my questions / comments.

2020-02-19 00:16 UTC, diego-codes commented
Thanks, @NicMoe! This is ready to review again.

2020-05-04 02:55 UTC, NicMoe approved these changes
Looks good!

2020-05-16 17:58 UTC, merged