Rotisserie chick sweet potato
diego-codes/recipes pull request #9
Opened 2020-04-25 16:15 UTC by diego-codes

2020-05-04 02:44 UTC, NicMoe requested changes
Rotisserie chicken and sweet potatoes are two different things. Maybe we could consider a section called "meals" where we recommend multiple recipes together, but I think we should split these up.

2020-05-16 18:06 UTC, diego-codes commented
Thanks,  @NicMoe this is ready to review again.

2020-05-16 19:39 UTC, NicMoe commented on meals/rotisserie-chicken-sweet-potato.md
> +- Roasted sweet potato havles ([recipe](../sides/roasted-sweet-potato-halves.md))
```suggestion
- Roasted sweet potato halves ([recipe](../sides/roasted-sweet-potato-halves.md))
```

2020-05-16 19:40 UTC, NicMoe commented on meals/rotisserie-chicken-sweet-potato.md
> +7. Serve veggies, chicken, tortillas, and sauce. Enjoy!
```suggestion
4. Serve veggies, chicken, tortillas, and sauce. Enjoy!
```

2020-05-16 19:41 UTC, NicMoe commented on sides/roasted-sweet-potato-halves.md
> +- Olive oil
How much oil, salt, pepper, and spices?

2020-05-16 19:41 UTC, NicMoe commented on sides/roasted-sweet-potato-halves.md
> +2. Coat all prepped veggies (sweet potato havles, onion quarters, and whole garlic cloves) with olive oil and salt, pepper, and spices to taste.
```suggestion
2. Coat all prepped veggies (sweet potato halves, onion quarters, and whole garlic cloves) with olive oil and salt, pepper, and spices to taste.
```

2020-05-16 19:43 UTC, NicMoe commented on sides/roasted-sweet-potato-halves.md
> +2. Coat all prepped veggies (sweet potato havles, onion quarters, and whole garlic cloves) with olive oil and salt, pepper, and spices to taste.
How much of each of these is recommended? "To taste" is nice, but giving readers a baseline to modify from is better.

2020-09-12 20:18 UTC, diego-codes commented
This PR is ready to review again, @NicMoe. Thank you!

2020-09-12 23:29 UTC, NicMoe approved these changes

2020-09-12 23:30 UTC, merged